/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppAdd {}
  interface AppAddAttributes extends StencilHTMLAttributes {}

  interface AppDelete {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppDeleteAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppDetails {
    'match': MatchResults;
  }
  interface AppDetailsAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppEdite {
    'match': MatchResults;
  }
  interface AppEditeAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppFooter {}
  interface AppFooterAttributes extends StencilHTMLAttributes {}

  interface AppHeader {}
  interface AppHeaderAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppPosts {}
  interface AppPostsAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface CustomClock {}
  interface CustomClockAttributes extends StencilHTMLAttributes {}

  interface MyFirstComponent {
    'name': string;
  }
  interface MyFirstComponentAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppAdd': Components.AppAdd;
    'AppDelete': Components.AppDelete;
    'AppDetails': Components.AppDetails;
    'AppEdite': Components.AppEdite;
    'AppFooter': Components.AppFooter;
    'AppHeader': Components.AppHeader;
    'AppHome': Components.AppHome;
    'AppPosts': Components.AppPosts;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'CustomClock': Components.CustomClock;
    'MyFirstComponent': Components.MyFirstComponent;
  }

  interface StencilIntrinsicElements {
    'app-add': Components.AppAddAttributes;
    'app-delete': Components.AppDeleteAttributes;
    'app-details': Components.AppDetailsAttributes;
    'app-edite': Components.AppEditeAttributes;
    'app-footer': Components.AppFooterAttributes;
    'app-header': Components.AppHeaderAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-posts': Components.AppPostsAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'custom-clock': Components.CustomClockAttributes;
    'my-first-component': Components.MyFirstComponentAttributes;
  }


  interface HTMLAppAddElement extends Components.AppAdd, HTMLStencilElement {}
  var HTMLAppAddElement: {
    prototype: HTMLAppAddElement;
    new (): HTMLAppAddElement;
  };

  interface HTMLAppDeleteElement extends Components.AppDelete, HTMLStencilElement {}
  var HTMLAppDeleteElement: {
    prototype: HTMLAppDeleteElement;
    new (): HTMLAppDeleteElement;
  };

  interface HTMLAppDetailsElement extends Components.AppDetails, HTMLStencilElement {}
  var HTMLAppDetailsElement: {
    prototype: HTMLAppDetailsElement;
    new (): HTMLAppDetailsElement;
  };

  interface HTMLAppEditeElement extends Components.AppEdite, HTMLStencilElement {}
  var HTMLAppEditeElement: {
    prototype: HTMLAppEditeElement;
    new (): HTMLAppEditeElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppPostsElement extends Components.AppPosts, HTMLStencilElement {}
  var HTMLAppPostsElement: {
    prototype: HTMLAppPostsElement;
    new (): HTMLAppPostsElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCustomClockElement extends Components.CustomClock, HTMLStencilElement {}
  var HTMLCustomClockElement: {
    prototype: HTMLCustomClockElement;
    new (): HTMLCustomClockElement;
  };

  interface HTMLMyFirstComponentElement extends Components.MyFirstComponent, HTMLStencilElement {}
  var HTMLMyFirstComponentElement: {
    prototype: HTMLMyFirstComponentElement;
    new (): HTMLMyFirstComponentElement;
  };

  interface HTMLElementTagNameMap {
    'app-add': HTMLAppAddElement
    'app-delete': HTMLAppDeleteElement
    'app-details': HTMLAppDetailsElement
    'app-edite': HTMLAppEditeElement
    'app-footer': HTMLAppFooterElement
    'app-header': HTMLAppHeaderElement
    'app-home': HTMLAppHomeElement
    'app-posts': HTMLAppPostsElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'custom-clock': HTMLCustomClockElement
    'my-first-component': HTMLMyFirstComponentElement
  }

  interface ElementTagNameMap {
    'app-add': HTMLAppAddElement;
    'app-delete': HTMLAppDeleteElement;
    'app-details': HTMLAppDetailsElement;
    'app-edite': HTMLAppEditeElement;
    'app-footer': HTMLAppFooterElement;
    'app-header': HTMLAppHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-posts': HTMLAppPostsElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'custom-clock': HTMLCustomClockElement;
    'my-first-component': HTMLMyFirstComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
